# Run from the repository root:
#   docker compose -f docker/compose.slim.yml up
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - ..:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
